# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.outbox = QtWidgets.QGroupBox(self.centralwidget)
        self.outbox.setStyleSheet("QGroupBox#outbox{\n"
"    border : 5px solid rgb(0, 149, 205);\n"
"    background-color: rgb(236, 241,244);\n"
"}")
        self.outbox.setTitle("")
        self.outbox.setObjectName("outbox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.outbox)
        self.gridLayout_6.setContentsMargins(20, 20, 20, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.depart = QtWidgets.QGroupBox(self.outbox)
        self.depart.setStyleSheet("#depart{\n"
"    border : 0px;\n"
"    background-color:white;\n"
"}")
        self.depart.setTitle("")
        self.depart.setObjectName("depart")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.depart)
        self.gridLayout_4.setContentsMargins(20, -1, -1, -1)
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.depart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕OTF")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.depart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setStyleSheet("#groupBox_2{border :0px; padding:0px}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setContentsMargins(3, -1, -1, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.combo_year = QtWidgets.QComboBox(self.groupBox_2)
        self.combo_year.setObjectName("combo_year")
        self.gridLayout_5.addWidget(self.combo_year, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕OTF")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 1, 1, 1, 1)
        self.combo_month = QtWidgets.QComboBox(self.groupBox_2)
        self.combo_month.setObjectName("combo_month")
        self.gridLayout_5.addWidget(self.combo_month, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕OTF")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 3, 1, 1)
        self.combo_day = QtWidgets.QComboBox(self.groupBox_2)
        self.combo_day.setObjectName("combo_day")
        self.gridLayout_5.addWidget(self.combo_day, 0, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕OTF")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 1, 1, 1)
        self.combo_hour_from = QtWidgets.QComboBox(self.groupBox_2)
        self.combo_hour_from.setObjectName("combo_hour_from")
        self.gridLayout_5.addWidget(self.combo_hour_from, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕OTF")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 5, 1, 1)
        self.combo_hour_to = QtWidgets.QComboBox(self.groupBox_2)
        self.combo_hour_to.setObjectName("combo_hour_to")
        self.gridLayout_5.addWidget(self.combo_hour_to, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕OTF")
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 1, 3, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 2, 1, 1)
        self.gridLayout_6.addWidget(self.depart, 2, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.outbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setStyleSheet("QGroupBox{border:0px}")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_10.addWidget(self.groupBox_6, 0, 2, 1, 1)
        self.status = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        self.status.setText("")
        self.status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.status.setObjectName("status")
        self.gridLayout_10.addWidget(self.status, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_10.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_4, 6, 1, 1, 1)
        self.tour = QtWidgets.QGroupBox(self.outbox)
        self.tour.setStyleSheet("#tour{\n"
"    border : 0px;\n"
"    background-color:white;\n"
"}")
        self.tour.setTitle("")
        self.tour.setObjectName("tour")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tour)
        self.gridLayout_3.setContentsMargins(20, -1, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.tour)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕OTF")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tour)
        self.groupBox.setStyleSheet("QGroupBox{\n"
"    border:0px\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_8.addWidget(self.lineEdit, 0, 3, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_8.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_8.addWidget(self.lineEdit_2, 0, 2, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_8.addWidget(self.lineEdit_4, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tour)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕OTF")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tour)
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"    border:0px\n"
"}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.combo_person = QtWidgets.QComboBox(self.groupBox_3)
        self.combo_person.setObjectName("combo_person")
        self.gridLayout_9.addWidget(self.combo_person, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.tour, 4, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.outbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setStyleSheet("QGroupBox{\n"
"    border : 0px;\n"
"    margin : 0px;\n"
"    padding : 0px\n"
"}")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕OTF")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border : 0px solid black;\n"
"    color : white;\n"
"    background : qlineargradient(spread:pad, x1:1, y1:0.1, x2:1, y2:0.9, stop:0 rgb(54, 124, 230), stop:1 rgba(39, 110, 202));\n"
"    padding : 5px;\n"
"}\n"
"\n"
"QPushButton::hover{border : 10px;}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout_6.addWidget(self.groupBox_5, 5, 1, 1, 1)
        self.station = QtWidgets.QGroupBox(self.outbox)
        self.station.setStyleSheet("#station{\n"
"    border : 0px;\n"
"    background-color:white;\n"
"}")
        self.station.setTitle("")
        self.station.setObjectName("station")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.station)
        self.gridLayout_7.setContentsMargins(20, -1, -1, -1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_6 = QtWidgets.QLabel(self.station)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕OTF")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.station)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕OTF")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 1, 0, 1, 1)
        self.combo_departure = QtWidgets.QComboBox(self.station)
        self.combo_departure.setObjectName("combo_departure")
        self.gridLayout_7.addWidget(self.combo_departure, 0, 1, 1, 1)
        self.combo_destination = QtWidgets.QComboBox(self.station)
        self.combo_destination.setObjectName("combo_destination")
        self.gridLayout_7.addWidget(self.combo_destination, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 0, 2, 1, 1)
        self.gridLayout_6.addWidget(self.station, 3, 1, 1, 1)
        self.car_type = QtWidgets.QGroupBox(self.outbox)
        self.car_type.setStyleSheet("#car_type{\n"
"    border : 0px;\n"
"    background-color:white;\n"
"}")
        self.car_type.setTitle("")
        self.car_type.setObjectName("car_type")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.car_type)
        self.gridLayout_2.setContentsMargins(20, -1, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 2, 1, 1)
        self.radio_ktx = QtWidgets.QRadioButton(self.car_type)
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕OTF")
        font.setPointSize(14)
        self.radio_ktx.setFont(font)
        self.radio_ktx.setObjectName("radio_ktx")
        self.gridLayout_2.addWidget(self.radio_ktx, 0, 3, 1, 1)
        self.radio_all = QtWidgets.QRadioButton(self.car_type)
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕OTF")
        font.setPointSize(14)
        self.radio_all.setFont(font)
        self.radio_all.setObjectName("radio_all")
        self.gridLayout_2.addWidget(self.radio_all, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.car_type)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕OTF")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 4, 1, 1)
        self.radio_flower = QtWidgets.QRadioButton(self.car_type)
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕OTF")
        font.setPointSize(14)
        self.radio_flower.setFont(font)
        self.radio_flower.setObjectName("radio_flower")
        self.gridLayout_2.addWidget(self.radio_flower, 0, 5, 1, 1)
        self.gridLayout_6.addWidget(self.car_type, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.outbox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "출발일"))
        self.label_9.setText(_translate("MainWindow", "시~"))
        self.label_5.setText(_translate("MainWindow", "월"))
        self.label_4.setText(_translate("MainWindow", "년"))
        self.label_10.setText(_translate("MainWindow", "일"))
        self.label_11.setText(_translate("MainWindow", "시"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.label_2.setText(_translate("MainWindow", "인원"))
        self.label_8.setText(_translate("MainWindow", "카드번호"))
        self.pushButton.setText(_translate("MainWindow", "티켓 예매하기"))
        self.label_6.setText(_translate("MainWindow", "출발역"))
        self.label_7.setText(_translate("MainWindow", "도착역"))
        self.radio_ktx.setText(_translate("MainWindow", "KTX/KTX-산천"))
        self.radio_all.setText(_translate("MainWindow", "전체"))
        self.label.setText(_translate("MainWindow", "차종"))
        self.radio_flower.setText(_translate("MainWindow", "무궁화호"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
